version: "3.9"
services:
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ${PWD}/web_directory:/usr/share/nginx/html     
  db:
    image: mysql:latest
    container_name: mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
volumes:
  db-data:
